Cypress.Commands.add('login', () => {
  cy.visit('/')
    .get('#email')
    .type('chrille@yo')
    .get('#password')
    .type('1234hahaha')
    .get(`[type="submit"]`)
    .click()
    .wait(500)
})
