---
# Source: drone/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: drone
  labels:
    app.kubernetes.io/name: drone
    helm.sh/chart: drone-0.1.0
    app.kubernetes.io/instance: drone
    app.kubernetes.io/version: '1.0'
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: drone
    app.kubernetes.io/instance: drone

---
# Source: drone/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  labels:
    app.kubernetes.io/name: drone
    helm.sh/chart: drone-0.1.0
    app.kubernetes.io/instance: drone
    app.kubernetes.io/version: '1.0'
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
      app.kubernetes.io/instance: drone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone
        app.kubernetes.io/instance: drone
    spec:
      containers:
        - name: drone
          image: 'iteam1337/brevduvor-drone:latest'
          imagePullPolicy: Always
          env:
            - name: OSRM_HOST
              value: http://osrm.default.svc.cluster.local
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          resources: {}

---
# Source: drone/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drone
  labels:
    app.kubernetes.io/name: drone
    helm.sh/chart: drone-0.1.0
    app.kubernetes.io/instance: drone
    app.kubernetes.io/version: '1.0'
    app.kubernetes.io/managed-by: Tiller
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  tls:
    - hosts:
        - 'drone.brevduvor.iteamdev.se'
      secretName: drone-letsencrypt-prod
  rules:
    - host: 'drone.brevduvor.iteamdev.se'
      http:
        paths:
          - path: /
            backend:
              serviceName: drone
              servicePort: http
