---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: client-letsencrypt-prod
spec:
  secretName: client-letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingressClass: traefik
        domains:
          - client.brevduvor.iteamdev.se
  dnsNames:
    - client.brevduvor.iteamdev.se
