---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: drone-letsencrypt-prod
spec:
  secretName: drone-letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingressClass: traefik
        domains:
          - drone.brevduvor.iteamdev.se
  dnsNames:
    - drone.brevduvor.iteamdev.se
