name: E2E

on:
  # TODO: do this on push to master
  pull_request:
    branches:
      - master

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start the API (with services)
        run: |
          cd packages/api
          npm install
          docker-compose up -d
          npm run start && npx wait-on http://localhost:4000 && npm run generate

  drone_simulator:
    needs: [api]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start the drone-simulator
        run: |
          cd packages/drone-simulator
          npm install
          npm run start

  cypress:
    needs: [api, drone_simulator]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Cypress-tests
        run: |
          cd packages/client
          npm install
          npm run cypress:run
