name: E2E

on:
  push:
    branches:
      - chore/e2e-ci

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      # - uses: actions/checkout@v1
      # - name: Cache osrm data
      #   uses: actions/cache@v1
      #   with:
      #     path: data
      #     key: ${{ runner.OS }}-build-${{ hashFiles('data.osrm.*') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-build-${{ env.cache-name }}-
      #       ${{ runner.OS }}-build-
      #       ${{ runner.OS }}-
      - name: Start osrm services
        run: docker-compose -f docker-compose.e2e.yml up -d osrm
      - name: Build the Drone-simulator image
        run: |
          cd packages/drone-simulator
          docker build -t brevduvor-drone:ci .
      - name: Build the API image
        run: |
          cd packages/api
          docker build -t brevduvor-api:ci .
      - name: Build the Client image
        run: |
          cd packages/client
          docker build -t brevduvor-client:ci --build-arg MAPBOX_TOKEN=$MAPBOX_TOKEN --build-arg GRAPHQL_API=http://api:4000/graphql --build-arg GRAPHQL_WS_URI=ws://api:4000/graphql .
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
      - name: Start remaining services
        run: |
          docker-compose -f docker-compose.e2e.yml up -d postgres api client
      - name: Run Cypresstests
        run: |
          docker-compose -f docker-compose.e2e.yml up cypress
