name: E2E

on:
  # TODO: do this on push to master
  pull_request:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Drone-simulator image
        run: |
          cd packages/drone-simulator
          docker build . --iidfile TEMP_DRONE_IMAGE_ID.txt
          DRONE_DOCKER_IMAGE_ID=$(cat TEMP_DRONE_IMAGE_ID.txt) 
          echo '::set-env name=DRONE_DOCKER_IMAGE_ID::$DRONE_DOCKER_IMAGE_ID'
      - name: Build the API image
        run: |
          cd packages/api
          docker build . --iidfile TEMP_API_IMAGE_ID.txt
          API_DOCKER_IMAGE_ID=$(cat TEMP_API_IMAGE_ID.txt) 
          echo '::set-env name=API_DOCKER_IMAGE_ID::$API_DOCKER_IMAGE_ID'
      - name: Start all services
        run: |
          cd packages/api
          docker-compose -f docker-compose-ci.yml up -d
      - name: Run Cypress-tests
        run: |
          cd packages/client
          npm install
          npm run cypress:run
        env:
          CI: true
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          GRAPHQL_API: http://localhost:4000/graphql
          GRAPHQL_WS_URI: ws://localhost:4000/graphql
