name: E2E

on:
  # TODO: do this on push to master
  pull_request:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - name: Build the Drone-simulator image
        id: drone
        run: |
          cd packages/drone-simulator
          docker build -t brevduvor-drone:ci .
      - name: Build the API image
        id: api
        run: |
          cd packages/api
          docker build -t brevduvor-api:ci .
      - name: Start all services
        run: |
          cd packages/client
          docker-compose -f docker-compose-ci.yml up -d
      - name: Bootstrap client
        run: |
          cd packages/client
          npm install
      - name: Run Cypress-tests
        run: |
          cd packages/client
          npm run cypress:run
        # - name: Commit & push Cypress-videos
        #   if: always()
        #   run: |
        #     git config --global user.name ${{ secrets.GITHUB_USER }}
        #     git config --global user.email ${{ secrets.GITHUB_EMAIL }}
        #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        #     echo ${GITHUB_HEAD_REF}
        #     git checkout "${GITHUB_HEAD_REF}"
        #     git add packages/client/cypress/videos
        #     git commit -m "test(e2e): submit cypress-videos"
        #     git push
        env:
          CI: true
          NODE_ENV: production
