name: PR-Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.13.0]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bootstrap dependencies
        run: |
          npm install
          npm run bootstrap
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          TWILIO__ACCOUNT: ${{ secrets.TWILIO__ACCOUNT }}
          TWILIO__TOKEN": ${{ secrets.TWILIO__TOKEN }}
          TWILIO__SENDER: '+15005550006'
          REDIS__PASSWORD: ${{ secrets.REDIS__PASSWORD }}
          JWT_PRIVATE_KEY: 'MYSECRETKEY'
          CI: 'true'
